### ISSUE TITLE
I keep on getting this crash when I open the radar station on a server.

### ISSUE THREAD

**Issue by Robot-Gentleman** [aidancbrady/DefenseTech#60]
---- Minecraft Crash Report ----
// Sorry :(

Time: 7/25/16 10:28 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by xTheDawg** [comment]
Having a similar Issue. Minecraft (sometimes) crashes after rightclicking on the Radarstation. Not sure if the Crash Report is the same though.
